In [1]:
pip install --upgrade pip

  Using cached pip-24.2-py3-none-any.whl.metadata (3.6 kB)
Using cached pip-24.2-py3-none-any.whl (1.8 MB)
  Attempting uninstall: pip
    Found existing installation: pip 24.1.2
    Uninstalling pip-24.1.2:
      Successfully uninstalled pip-24.1.2


In [2]:
pip install tensorflow

In [5]:
import tensorflow as tf
print(tf.__version__)

2.17.0


In [9]:
scaler = tf.constant(5,6)
scaler

<tf.Tensor: shape=(), dtype=int8, numpy=5>

In [10]:
scaler.ndim

0

In [21]:
vector = tf.constant([[5,6],[5,6]])
vector

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 6],
       [5, 6]], dtype=int32)>

In [22]:
vector.ndim

2

In [28]:
vector = tf.constant([[[5,6],[5,6],[5,6]]],dtype= tf.int16)
vector.ndim
vector

<tf.Tensor: shape=(1, 3, 2), dtype=int16, numpy=
array([[[5, 6],
        [5, 6],
        [5, 6]]], dtype=int16)>

In [36]:
matrix = tf.constant([[[10,6],[10,6],[10,6]]],dtype=tf.int16)
matrix

<tf.Tensor: shape=(1, 3, 2), dtype=int16, numpy=
array([[[10,  6],
        [10,  6],
        [10,  6]]], dtype=int16)>

In [35]:
matrix.ndim

3

In [40]:
matrix = tf.constant([[[10.5,6.10],[10.5,6.10],[10.5,6.10]]],dtype=tf.float32)
matrix

<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[10.5,  6.1],
        [10.5,  6.1],
        [10.5,  6.1]]], dtype=float32)>

In [39]:
matrix.ndim

3

In [49]:
tensor = tf.constant([[[[1,2,3],[2,3,4]],[[6,4,3],[2,3,4]],[[3,2,3],[2,4,3]]]])
tensor

<tf.Tensor: shape=(1, 3, 2, 3), dtype=int32, numpy=
array([[[[1, 2, 3],
         [2, 3, 4]],

        [[6, 4, 3],
         [2, 3, 4]],

        [[3, 2, 3],
         [2, 4, 3]]]], dtype=int32)>

In [50]:
tensor.ndim

4